name: 'ğŸš€ CD â€” Publish'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event.repository.fork == false
    name: Release Please
    steps:
      - name: ğŸ¤ Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}
          config-file: .github/release/config.json
          manifest-file: .github/release/manifest.json

      - name: â• Actions - Checkout
        uses: actions/checkout@v6
        if: ${{ steps.release.outputs.release_created }}

      - name: â• Actions - Setup Node.js
        uses: actions/setup-node@v6
        if: ${{ steps.release.outputs.release_created }}
        with:
          check-latest: true
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'

      - name: â• Cache dependencies
        uses: actions/cache@v5
        if: ${{ steps.release.outputs.release_created }}
        with:
          path: ~/.npm
          key: npm-linux-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-linux-

      - name: ğŸ“¦ Installing Dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: ğŸš€ Building Poku
        if: ${{ steps.release.outputs.release_created }}

        run: npm run build

      - name: ğŸ“¥ Publishing Package
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance

      - name: ğŸ”— Triggering â€” Website Publish
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'cd_docs-deploy.yml',
              ref: 'main'
            });
