name: 'ğŸ CI â€” Coverage'

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  node:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    name: macOS & Node.js
    steps:
      - name: â• Actions - Checkout
        uses: actions/checkout@v4

      - name: â• Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-osx-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-osx-

      - name: â• Actions - Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: ğŸ“¦ Installing Dependencies
        run: npm ci

      - name: ğŸ§ª Checking for Coverage
        run: npm run test:c8

      - name: â˜”ï¸ Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: osx-nodejs
          name: codecov-umbrella-osx-node

  node-options:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    name: macOS & Node.js (Options)
    steps:
      - name: â• Actions - Checkout
        uses: actions/checkout@v4

      - name: â• Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-osx-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-osx-

      - name: â• Actions - Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: ğŸ“¦ Installing Dependencies
        run: npm ci

      - name: ğŸ§ª Checking for Coverage
        run: npm run test:c8:options

      - name: â˜”ï¸ Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: osx-nodejs-options
          name: codecov-umbrella-osx-node-options
