name: 'ğŸ CI â€” Coverage'

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  sequential:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    name: macOS (Sequential)
    steps:
      - name: â• Actions - Checkout
        uses: actions/checkout@v4

      - name: â• Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-osx-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-osx-

      - name: â• Actions - Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: ğŸ“¦ Installing Dependencies
        run: npm ci

      - name: ğŸ§ª Checking for Coverage
        run: npm run test:c8:sequential

      - name: â˜”ï¸ Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: osx-sequential
          name: codecov-umbrella-osx-sequential

  sequential-options:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    name: macOS (Sequential & Options)
    steps:
      - name: â• Actions - Checkout
        uses: actions/checkout@v4

      - name: â• Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-osx-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-osx-

      - name: â• Actions - Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: ğŸ“¦ Installing Dependencies
        run: npm ci

      - name: ğŸ§ª Checking for Coverage
        run: npm run test:c8:sequential:options

      - name: â˜”ï¸ Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: osx-sequential-options
          name: codecov-umbrella-osx-sequential-options

  parallel:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    name: macOS (Parallel)
    steps:
      - name: â• Actions - Checkout
        uses: actions/checkout@v4

      - name: â• Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-osx-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-osx-

      - name: â• Actions - Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: ğŸ“¦ Installing Dependencies
        run: npm ci

      - name: ğŸ§ª Checking for Coverage
        run: npm run test:c8:parallel

      - name: â˜”ï¸ Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: osx-parallel
          name: codecov-umbrella-osx-parallel

  parallel-options:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    name: macOS (Parallel & Options)
    steps:
      - name: â• Actions - Checkout
        uses: actions/checkout@v4

      - name: â• Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-osx-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-osx-

      - name: â• Actions - Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: ğŸ“¦ Installing Dependencies
        run: npm ci

      - name: ğŸ§ª Checking for Coverage
        run: npm run test:c8:parallel:options

      - name: â˜”ï¸ Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: osx-parallel-options
          name: codecov-umbrella-osx-parallel-options
